# Generated by Django 5.2.8 on 2026-01-30 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('STUDENT', 'Student'), ('COLLEGE_ADMIN', 'College Administrator'), ('SUPER_ADMIN', 'Super Administrator')], default='STUDENT', max_length=20),
        ),
    ]
