# Generated by Django 5.2.8 on 2026-01-30 09:57

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('colleges', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('course_code', models.CharField(db_index=True, max_length=20)),
                ('course_title', models.CharField(max_length=200)),
                ('course_description', models.TextField(blank=True)),
                ('year_level', models.CharField(choices=[('first_year', 'First Year'), ('second_year', 'Second Year'), ('third_year', 'Third Year'), ('fourth_year', 'Fourth Year'), ('fifth_year', 'Fifth Year')], max_length=20)),
                ('semester', models.CharField(choices=[('first_sem', 'First Semester/Trimester'), ('second_sem', 'Second Semester/Trimester'), ('third_sem', 'Third Semester/Trimester'), ('summer', 'Summer Term'), ('special', 'Special Term')], max_length=20)),
                ('units', models.DecimalField(decimal_places=1, default=3.0, max_digits=3)),
                ('lecture_hours', models.PositiveIntegerField(default=0)),
                ('laboratory_hours', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('is_core', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='colleges.program')),
            ],
            options={
                'db_table': 'courses',
                'ordering': ['course_code'],
            },
        ),
        migrations.CreateModel(
            name='CoursePrerequisite',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_strict', models.BooleanField(default=True)),
                ('minimum_grade', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='required_for', to='courses.course')),
                ('prerequisite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prerequisite_for', to='courses.course')),
            ],
            options={
                'db_table': 'course_prerequisites',
                'unique_together': {('course', 'prerequisite')},
            },
        ),
        migrations.AddField(
            model_name='course',
            name='prerequisites',
            field=models.ManyToManyField(blank=True, through='courses.CoursePrerequisite', to='courses.course'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['program', 'year_level', 'semester'], name='courses_program_4bffe0_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='course',
            unique_together={('program', 'course_code')},
        ),
    ]
