# Generated by Django 5.2.8 on 2026-01-26 03:22

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('colleges', '0001_initial'),
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolYear',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_active', models.BooleanField(default=False)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'db_table': 'school_years',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='ScheduleGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('year_level', models.CharField(choices=[('first_year', 'First Year'), ('second_year', 'Second Year'), ('third_year', 'Third Year'), ('fourth_year', 'Fourth Year'), ('fifth_year', 'Fifth Year')], max_length=20)),
                ('section', models.CharField(max_length=10)),
                ('semester', models.CharField(choices=[('first_sem', 'First Semester/Trimester'), ('second_sem', 'Second Semester/Trimester'), ('third_sem', 'Third Semester/Trimester'), ('summer', 'Summer Term'), ('special', 'Special Term')], max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending Approval'), ('approved', 'Approved'), ('active', 'Active'), ('archived', 'Archived'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('approval_date', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_schedule_groups', to='accounts.userprofile')),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='colleges.college')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_schedule_groups', to='accounts.userprofile')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='colleges.program')),
                ('school_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduling.schoolyear')),
            ],
            options={
                'db_table': 'schedule_groups',
                'ordering': ['school_year', 'semester', 'program', 'year_level', 'section'],
            },
        ),
        migrations.CreateModel(
            name='ScheduleItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('day', models.CharField(choices=[('MON', 'Monday'), ('TUE', 'Tuesday'), ('WED', 'Wednesday'), ('THU', 'Thursday'), ('FRI', 'Friday'), ('SAT', 'Saturday'), ('SUN', 'Sunday')], max_length=3)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('room', models.CharField(max_length=50)),
                ('instructor_override', models.CharField(blank=True, max_length=100)),
                ('max_students', models.PositiveIntegerField(default=40)),
                ('current_enrollment', models.PositiveIntegerField(default=0)),
                ('is_lab', models.BooleanField(default=False)),
                ('is_online', models.BooleanField(default=False)),
                ('online_link', models.URLField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course')),
                ('instructor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.staffprofile')),
                ('schedule_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='scheduling.schedulegroup')),
            ],
            options={
                'db_table': 'schedule_items',
                'ordering': ['day', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='ScheduleConflict',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('conflict_type', models.CharField(choices=[('room', 'Room Conflict'), ('instructor', 'Instructor Conflict'), ('section', 'Section Conflict'), ('student', 'Student Conflict'), ('time_overlap', 'Time Overlap')], max_length=20)),
                ('severity', models.PositiveIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('description', models.TextField()),
                ('resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_notes', models.TextField(blank=True)),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.userprofile')),
                ('schedule_item_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conflicts_as_first', to='scheduling.scheduleitem')),
                ('schedule_item_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conflicts_as_second', to='scheduling.scheduleitem')),
            ],
            options={
                'db_table': 'schedule_conflicts',
            },
        ),
        migrations.AddIndex(
            model_name='scheduleitem',
            index=models.Index(fields=['schedule_group', 'day', 'start_time'], name='schedule_it_schedul_e8a020_idx'),
        ),
        migrations.AddIndex(
            model_name='scheduleitem',
            index=models.Index(fields=['room', 'day', 'start_time'], name='schedule_it_room_407c40_idx'),
        ),
        migrations.AddIndex(
            model_name='scheduleitem',
            index=models.Index(fields=['instructor', 'day', 'start_time'], name='schedule_it_instruc_7ec48e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='scheduleconflict',
            unique_together={('schedule_item_1', 'schedule_item_2', 'conflict_type')},
        ),
        migrations.AlterUniqueTogether(
            name='schedulegroup',
            unique_together={('program', 'year_level', 'section', 'semester', 'school_year')},
        ),
    ]
