# Generated by Django 5.2.8 on 2026-01-23 01:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100)),
                ('user_role', models.CharField(max_length=50)),
                ('activity_type', models.CharField(choices=[('login', 'User Login'), ('logout', 'User Logout'), ('schedule_create', 'Schedule Created'), ('schedule_update', 'Schedule Updated'), ('schedule_delete', 'Schedule Deleted'), ('user_register', 'User Registration'), ('bulk_schedule', 'Bulk Schedule Operation')], max_length=50)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('details', models.JSONField(default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp'], name='activity_lo_timesta_c26c07_idx'), models.Index(fields=['user'], name='activity_lo_user_id_7b8207_idx'), models.Index(fields=['activity_type'], name='activity_lo_activit_dd4400_idx')],
            },
        ),
    ]
