# Generated by Django 5.2.8 on 2026-01-23 01:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('dean_name', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('BSIT', 'BS Information Technology'), ('BSCE', 'BS Computer Engineering'), ('BSGE', 'BS Geodetic Engineering'), ('BSCpE', 'BS Computer Engineering')], max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='core.department')),
            ],
            options={
                'unique_together': {('code', 'department')},
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('units', models.IntegerField(default=3)),
                ('year_level', models.CharField(choices=[('first_year', 'First Year'), ('second_year', 'Second Year'), ('third_year', 'Third Year'), ('fourth_year', 'Fourth Year')], max_length=20)),
                ('semester', models.CharField(choices=[('first_sem', 'First Semester'), ('second_sem', 'Second Semester'), ('third_sem', 'Third Semester')], max_length=20)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='core.program')),
            ],
            options={
                'ordering': ['year_level', 'semester', 'code'],
                'unique_together': {('code', 'program', 'year_level', 'semester')},
            },
        ),
    ]
